language: objective-c
osx_image: xcode8.2

before_install:
    - gem install xcpretty

script:
    - pod lib lint
    - rake build[ "test", "Twifter", "Twifter", "iphonesimulator10.2", "platform=iOS Simulator,name=iPhone 6s" ]

notifications:
    email: false
